/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Patrick Felipi Cursino Fonseca - TIA: 3125393-8
 */

import javax.swing.*;
import java.text.*;
import java.sql.*;

public class FormProcurarSupervisor_Alterar extends javax.swing.JFrame {
    static String retornoNome = null;
    static String retornoDRT = null;
    /**
     * Creates new form FormProcurarSupervisor_Alterar
     */
    public FormProcurarSupervisor_Alterar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupButton = new javax.swing.ButtonGroup();
        painel1 = new javax.swing.JPanel();
        labNome = new javax.swing.JLabel();
        txtNomeSupervisor = new javax.swing.JTextField();
        labCNPJ = new javax.swing.JLabel();
        txtDRT = new javax.swing.JTextField();
        rbNome = new javax.swing.JRadioButton();
        rbDRT = new javax.swing.JRadioButton();
        labSupervisorPor = new javax.swing.JLabel();
        btnProcurarSupervisor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Procurar Supervisor");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        painel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Supervisor:"));

        labNome.setText("NOME DO SUPERVISOR :");

        txtNomeSupervisor.setToolTipText("Inserir Nome do Supervisor");
        txtNomeSupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeSupervisorActionPerformed(evt);
            }
        });
        txtNomeSupervisor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeSupervisorKeyTyped(evt);
            }
        });

        labCNPJ.setText("DRT :");

        txtDRT.setToolTipText("Inserir DRT");
        txtDRT.setEnabled(false);
        txtDRT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDRTKeyTyped(evt);
            }
        });

        groupButton.add(rbNome);
        rbNome.setSelected(true);
        rbNome.setText("Nome");
        rbNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNomeActionPerformed(evt);
            }
        });

        groupButton.add(rbDRT);
        rbDRT.setText("DRT");
        rbDRT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDRTActionPerformed(evt);
            }
        });

        labSupervisorPor.setText("Procurar Supervisor Por :");
        labSupervisorPor.setToolTipText("");

        javax.swing.GroupLayout painel1Layout = new javax.swing.GroupLayout(painel1);
        painel1.setLayout(painel1Layout);
        painel1Layout.setHorizontalGroup(
            painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel1Layout.createSequentialGroup()
                        .addComponent(rbNome)
                        .addGap(83, 83, 83)
                        .addComponent(rbDRT))
                    .addGroup(painel1Layout.createSequentialGroup()
                        .addComponent(labNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNomeSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel1Layout.createSequentialGroup()
                        .addComponent(labCNPJ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDRT, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labSupervisorPor))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        painel1Layout.setVerticalGroup(
            painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labSupervisorPor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbNome)
                    .addComponent(rbDRT))
                .addGap(18, 18, 18)
                .addGroup(painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labNome)
                    .addComponent(txtNomeSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labCNPJ)
                    .addComponent(txtDRT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnProcurarSupervisor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botoes_Site_5746_Knob_Valid_Blue.png"))); // NOI18N
        btnProcurarSupervisor.setText("Procurar Supervisor");
        btnProcurarSupervisor.setToolTipText("Procurar Supervisor");
        btnProcurarSupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarSupervisorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProcurarSupervisor)
                .addGap(121, 121, 121))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProcurarSupervisor)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeSupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeSupervisorActionPerformed
        btnProcurarSupervisor.setEnabled(true);
    }//GEN-LAST:event_txtNomeSupervisorActionPerformed

    private void txtDRTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDRTKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
        int x = 0;
        String drt = txtDRT.getText();
        x = drt.length();
        if(x == 12){
            evt.consume();
        }
    }//GEN-LAST:event_txtDRTKeyTyped

    private void rbNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNomeActionPerformed
        if(rbNome.isSelected()){
            txtNomeSupervisor.setEnabled(true);
            txtDRT.setEnabled(false);
            txtNomeSupervisor.grabFocus();
            txtDRT.setText("");
        }else{
            txtNomeSupervisor.setEnabled(false);
        }
    }//GEN-LAST:event_rbNomeActionPerformed

    private void rbDRTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDRTActionPerformed
        if(rbDRT.isSelected()){
            txtDRT.setEnabled(true);
            txtNomeSupervisor.setEnabled(false);
            txtDRT.grabFocus();
            txtNomeSupervisor.setText("");
        }else{
            txtDRT.setEnabled(false);
        }
    }//GEN-LAST:event_rbDRTActionPerformed

    private void btnProcurarSupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarSupervisorActionPerformed
        String txt1 = txtNomeSupervisor.getText();
        String txt2 = txtDRT.getText();
        if (rbNome.isSelected() && txt1.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o NOME DO SUPERVISOR !!!", "Erro", JOptionPane.WARNING_MESSAGE);
            txtNomeSupervisor.grabFocus();
        } else if (rbDRT.isSelected() && txt2.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o DRT !!!", "Erro", JOptionPane.WARNING_MESSAGE);
            txtDRT.grabFocus();
        } else {
            if(rbNome.isSelected()){
                retornoNome = txtNomeSupervisor.getText();
            }
            if(rbDRT.isSelected()){
                retornoDRT = txtDRT.getText();
            }
            groupButton.clearSelection();
            txtNomeSupervisor.setText("");
            txtDRT.setText("");
            FormAlterarSupervisor alterarSupervisor = new FormAlterarSupervisor();
            alterarSupervisor.setLocationRelativeTo(null);
            alterarSupervisor.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnProcurarSupervisorActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        txtNomeSupervisor.grabFocus();
    }//GEN-LAST:event_formWindowOpened

    private void txtNomeSupervisorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeSupervisorKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isLetter(c)){
            if(!Character.isWhitespace(c)){
                evt.consume();
            }
        }
        int x = 0;
        String nome = txtNomeSupervisor.getText();
        x = nome.length();
        if(x == 45){
            evt.consume();
        }
    }//GEN-LAST:event_txtNomeSupervisorKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormProcurarSupervisor_Alterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormProcurarSupervisor_Alterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormProcurarSupervisor_Alterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormProcurarSupervisor_Alterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormProcurarSupervisor_Alterar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcurarSupervisor;
    private javax.swing.ButtonGroup groupButton;
    private javax.swing.JLabel labCNPJ;
    private javax.swing.JLabel labNome;
    private javax.swing.JLabel labSupervisorPor;
    private javax.swing.JPanel painel1;
    private javax.swing.JRadioButton rbDRT;
    private javax.swing.JRadioButton rbNome;
    private javax.swing.JTextField txtDRT;
    private javax.swing.JTextField txtNomeSupervisor;
    // End of variables declaration//GEN-END:variables
}
