/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Patrick Felipi Cursino Fonseca - TIA: 3125393-8
 */

import javax.swing.*;
import java.text.*;
import java.sql.*;

public class FormProcurarExame_Excluir extends javax.swing.JFrame {
    static String retornoNome = null;
    static String retornoCodigo = null;
    /**
     * Creates new form FormProcurarExame_Excluir
     */
    public FormProcurarExame_Excluir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupButton = new javax.swing.ButtonGroup();
        painel1 = new javax.swing.JPanel();
        labNome = new javax.swing.JLabel();
        txtNomeExame = new javax.swing.JTextField();
        labCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        rbNome = new javax.swing.JRadioButton();
        rbCodigo = new javax.swing.JRadioButton();
        labProcurarExamePor = new javax.swing.JLabel();
        btnProcurarExame = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Procurar Exame");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        painel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Exame:"));

        labNome.setText("NOME DO EXAME :");

        txtNomeExame.setToolTipText("Inserir Nome da CLínica");
        txtNomeExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeExameActionPerformed(evt);
            }
        });
        txtNomeExame.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeExameKeyTyped(evt);
            }
        });

        labCodigo.setText("CÓDIGO :");

        txtCodigo.setToolTipText("Inserir CNPJ");
        txtCodigo.setEnabled(false);
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });

        groupButton.add(rbNome);
        rbNome.setSelected(true);
        rbNome.setText("Nome");
        rbNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNomeActionPerformed(evt);
            }
        });

        groupButton.add(rbCodigo);
        rbCodigo.setText("CÓDIGO");
        rbCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCodigoActionPerformed(evt);
            }
        });

        labProcurarExamePor.setText("Procurar Exame Por :");
        labProcurarExamePor.setToolTipText("");

        javax.swing.GroupLayout painel1Layout = new javax.swing.GroupLayout(painel1);
        painel1.setLayout(painel1Layout);
        painel1Layout.setHorizontalGroup(
            painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel1Layout.createSequentialGroup()
                        .addComponent(rbNome)
                        .addGap(83, 83, 83)
                        .addComponent(rbCodigo))
                    .addGroup(painel1Layout.createSequentialGroup()
                        .addComponent(labNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNomeExame, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painel1Layout.createSequentialGroup()
                        .addComponent(labCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labProcurarExamePor))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        painel1Layout.setVerticalGroup(
            painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labProcurarExamePor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbNome)
                    .addComponent(rbCodigo))
                .addGap(18, 18, 18)
                .addGroup(painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labNome)
                    .addComponent(txtNomeExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnProcurarExame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botoes_Site_5746_Knob_Valid_Blue.png"))); // NOI18N
        btnProcurarExame.setText("Procurar Exame");
        btnProcurarExame.setToolTipText("Procurar Exame");
        btnProcurarExame.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnProcurarExameStateChanged(evt);
            }
        });
        btnProcurarExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarExameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProcurarExame)
                .addGap(131, 131, 131))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProcurarExame)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeExameActionPerformed
        btnProcurarExame.setEnabled(true);
    }//GEN-LAST:event_txtNomeExameActionPerformed

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
        int x = 0;
        String codigo = txtCodigo.getText();
        x = codigo.length();
        if(x == 11){
            evt.consume();
        }
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void rbNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNomeActionPerformed
        if(rbNome.isSelected()){
            txtNomeExame.setEnabled(true);
            txtCodigo.setEnabled(false);
            txtNomeExame.grabFocus();
            txtCodigo.setText("");
        }else{
            txtNomeExame.setEnabled(false);
        }
    }//GEN-LAST:event_rbNomeActionPerformed

    private void rbCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCodigoActionPerformed
        if(rbCodigo.isSelected()){
            txtCodigo.setEnabled(true);
            txtNomeExame.setEnabled(false);
            txtCodigo.grabFocus();
            txtNomeExame.setText("");
        }else{
            txtCodigo.setEnabled(false);
        }
    }//GEN-LAST:event_rbCodigoActionPerformed

    private void btnProcurarExameStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnProcurarExameStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProcurarExameStateChanged

    private void btnProcurarExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarExameActionPerformed
        String txt1 = txtNomeExame.getText();
        String txt2 = txtCodigo.getText();
        if (rbNome.isSelected() && txt1.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o NOME DO EXAME !!!", "Erro", JOptionPane.WARNING_MESSAGE);
            txtNomeExame.grabFocus();
        } else if (rbCodigo.isSelected() && txt2.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Informe o CÓDIGO !!!", "Erro", JOptionPane.WARNING_MESSAGE);
            txtCodigo.grabFocus();
        } else {
            if(rbNome.isSelected()){
                retornoNome = txtNomeExame.getText();
            }
            if(rbCodigo.isSelected()){
                retornoCodigo = txtCodigo.getText();
            }
            groupButton.clearSelection();
            txtNomeExame.setText("");
            txtCodigo.setText("");
            FormExcluirListaExame excluirListaExame = new FormExcluirListaExame();
            excluirListaExame.setLocationRelativeTo(null);
            excluirListaExame.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnProcurarExameActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        txtNomeExame.grabFocus();
    }//GEN-LAST:event_formWindowOpened

    private void txtNomeExameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeExameKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isLetter(c)){
            if(!Character.isWhitespace(c)){
                evt.consume();
            }
        }
        int x = 0;
        String nome = txtNomeExame.getText();
        x = nome.length();
        if(x == 45){
            evt.consume();
        }
    }//GEN-LAST:event_txtNomeExameKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormProcurarExame_Excluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormProcurarExame_Excluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormProcurarExame_Excluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormProcurarExame_Excluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormProcurarExame_Excluir().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcurarExame;
    private javax.swing.ButtonGroup groupButton;
    private javax.swing.JLabel labCodigo;
    private javax.swing.JLabel labNome;
    private javax.swing.JLabel labProcurarExamePor;
    private javax.swing.JPanel painel1;
    private javax.swing.JRadioButton rbCodigo;
    private javax.swing.JRadioButton rbNome;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNomeExame;
    // End of variables declaration//GEN-END:variables
}
